general.import = [
	"~/.config.after/alacritty/alacritty.after.toml",
    "~/.config/alacritty/colors.toml"
]

# Set these in the local file.
# [font]
# size = 10.0
# 
# [font.normal]
# family = "Hack"
# style = "Regular"

[window]
option_as_alt = "Both"
